use_frameworks!

target 'DBC_Example' do
	pod 'DBC', :path => '../'

  target 'DBC_Tests' do
    inherit! :search_paths
    pod 'DBC/Bridged', :path => '../'
	pod 'DBCTesting', :path => '../'
  end
end

post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		# Configure Pod targets for Xcode 8 compatibility
		config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'XE63Z2QPWQ/'
		
		if config.name == 'Debug'
			config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
			config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-DCOCOAPODS', '-DDEBUG']
		end
	end
	
	installer.pods_project.targets.each do |target|
		if target.name == 'DBC'
			target.build_configurations.each do |config|
				config.build_settings['SWIFT_VERSION'] = '3.0'
			end
		end
	end
end
