use_frameworks!

target 'DBC_Example' do
	pod 'DBC', :path => '../'

  target 'DBC_Tests' do
    inherit! :search_paths
	pod 'DBCTesting', :path => '../'

    
  end
end

post_install do |installer_representation|
	installer_representation.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			if config.name == 'Debug'
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] &&= ['$(inherited)', 'DEBUG=1']
				config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-DCOCOAPODS', '-DDEBUG']
			end
		end
	end
end
