use_frameworks!

target 'DBC_Example' do
	platform :ios, '9.0'
	pod 'DBC', :path => '../'

  target 'DBC_Tests' do
    inherit! :search_paths
    pod 'DBC/Bridged', :path => '../'
	pod 'DBCTesting', :path => '../'
  end
end

target 'DBC-tvOS' do
	platform :tvos, '9.2'
	pod 'DBC', :path => '../'
	
	target 'DBC-tvOSTests' do
		inherit! :search_paths
		pod 'DBC/Bridged', :path => '../'
		pod 'DBCTesting', :path => '../'
	end
end

target 'DBC-macOS' do
	platform :osx, '10.10'
	pod 'DBC', :path => '../'
	
	target 'DBC-macOSTests' do
		inherit! :search_paths
		pod 'DBC/Bridged', :path => '../'
		pod 'DBCTesting', :path => '../'
	end
end


post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		# Configure Pod targets for Xcode 8 compatibility
		config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = '6J53SQMFPY/'
		
		if config.name == 'Debug'
			config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
			config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-DCOCOAPODS', '-DDEBUG']
		end
	end
end
